const dataKos = [
  {
    "slug": "kost-adella",
    "nama_kost": "Kost Adella",
    "tipe": "CAMPURAN",
    "sisa_kamar": "1 Sisa Kamar",
    "harga": "Rp.2.500.000",
    "gambar_utama": "assets/kos_adella.png",
    "gambar_sub": "assets/kos_adella_2.png",
    "deskripsi": "kami menerima kost buat mingguan blnan. parkir luas penjaga 24 jam tipe kamar 3x6 fasilitas ac tv meja kursi lemari pakaian kamar mandi di dlm air panas dingin 24 jm free wifi dll....",
    "telepon": "089676104236",
    "alamat": "Jl. Demang II, Lorok Pakjo, Kec. Ilir Bar. I, Kota Palembang, Sumatera Selatan.",
    "kota": "palembang"
  },
  {
    "slug": "alkost-dramaga-bogor",
    "nama_kost": "Alkost Dramaga Bogor",
    "tipe": "WANITA",
    "sisa_kamar": "5 Sisa Kamar",
    "harga": "Rp. 850.000",
    "gambar_utama": "assets/kos_alkost_dramaga_bogor.png",
    "gambar_sub": "assets/kos_alkost_dramaga_bogor_2.jpg",
    "deskripsi": "Kost Putri dengan bangunan dan furniture serba baru. Tersedia 5 kamar dengan masing- masing memiliki kamar mandi dalam.Luas Kamar: 3 m x 3 m",
    "telepon": "082233445566",
    "alamat": "Jl. Babakan Raya 04 No.122E, RT.03/RW.07, Desa Babakan, Kec. Dramaga, Kab.Bogor, 16680.",
    "kota": "bogor"
  },
  {
    "slug": "barokah-a",
    "nama_kost": "Barokah A",
    "tipe": "CAMPURAN",
    "sisa_kamar": "10 Sisa Kamar",
    "harga": "Rp. 1.700.000",
    "gambar_utama": "assets/Barokah_A.png",
    "gambar_sub": "assets/Barokah_A_2.png",
    "deskripsi": "Kamar mandi dalam dengan shower, dapur untuk setiap kamar yang telah dilengkapi dengan kompor, kulkas, Sofa / kursi, meja, Lemari, AC, Tempat tidur, & bantal.Luas Kamar: 9 m x 3 m",
    "telepon": "082122345670",
    "alamat": "GG Citra Jalan Roda Pembangunan No. 20 Nanggewer Cibinong Bogor Jawa Barat.",
    "kota": "bogor"
  },
  {
    "slug": "bu-ita-kost",
    "nama_kost": "Bu Ita Kost",
    "tipe": "CAMPURAN",
    "sisa_kamar": "0 Sisa Kamar",
    "harga": "Rp.700.000",
    "gambar_utama": "assets/kos_bu_ita.png",
    "gambar_sub": "assets/kos_bu_ita.png",
    "deskripsi": "Bu Ita Kost berlokasi ditempat strategis, 5 menit ke UIN Raden Fatah serta tempat umum lainnya, cocok untuk anak kuliahan atau bekerja. Kamar dengan luas 3 x 8 Meter, tidak termasuk biaya listrik, kami juga memiliki fasilitas parkir untuk mobil, motor, dan sepeda.",
    "telepon": "08982019006",
    "alamat": "Lorong Karya I, 20 Ilir D II, Kec. Kemuning, Kota Palembang, Sumatera Selatan 30127",
    "kota": "palembang"
  },
  {
    "slug": "clemira-kost",
    "nama_kost": "Clemira Kost",
    "tipe": "WANITA",
    "sisa_kamar": "2 Sisa Kamar",
    "harga": "Rp. 1.600.000",
    "gambar_utama": "assets/clemira_kost_hero_1.png",
    "gambar_sub": "assets/clemira_kost_hero_2.png",
    "deskripsi": "Clemira Kost berlokasi ditempat strategis, 10 menit ke UNSRI dan POLSRI serta tempat umum lainnya, cocok untuk anak kuliahan atau bekerja. Kamar dengan luas 3 x 8 Meter, tidak termasuk biaya listrik, kami juga memiliki fasilitas parkir untuk mobil, motor, dan sepeda.",
    "telepon": "082282233692",
    "alamat": "Jalan Kancil Putih VI RT 46 RW 10 NO 4625, Demang Lebar Daun, Kec. Ilir Bar. I, Kota Palembang, Sumatera Selatan, Indonesia.",
    "kota": "palembang"
  },
  {
    "slug": "felicia-residence",
    "nama_kost": "Felicia Residence",
    "tipe": "WANITA",
    "sisa_kamar": "5 Sisa Kamar",
    "harga": "Rp. 600.000",
    "gambar_utama": "assets/felicia_residence.png",
    "gambar_sub": "assets/felicia_residence_2.png",
    "deskripsi": "Kost Putri Murah & Modern Gunung Sindur Dekat UNPAM Viktor 📍 Lokasi: Gunung Sindur, Bogor (dekat UNPAM Viktor, Tangerang Selatan)🏡 Khusus putri Cocok untuk mahasiswa/i dan karyawan yang mencari kost bersih, aman, dan hemat.Luas Kamar: 3 m x 3 m",
    "telepon": "081389955507",
    "alamat": "Felicia Residence, Blok B No 8, Jl Pendidikan, Rawakalong, Gunung Sindur Bogor, Terdekat Unpam Viktor Tangerang Selatan.",
    "kota": "bogor"
  },
  {
    "slug": "hillside-colony-bogor-c2-no-15",
    "nama_kost": "Hillside Colony Bogor C2 No. 15",
    "tipe": "CAMPURAN",
    "sisa_kamar": "1 Sisa Kamar",
    "harga": "Rp. 1.700.000",
    "gambar_utama": "assets/Hillside_colony_bogor.png",
    "gambar_sub": "assets/Hillside_colony_bogor_2.png",
    "deskripsi": "Hillside Colony Bogor C2 No. 15Luas Kamar: 3 m x 2 m",
    "telepon": "082240352276",
    "alamat": "Jl. Cilubang Ciomas Raya.",
    "kota": "bogor"
  },
  {
    "slug": "kost-ibu-iza",
    "nama_kost": "Kost Ibu Iza",
    "tipe": "WANITA",
    "sisa_kamar": "7 Sisa Kamar",
    "harga": "Rp. 550.000",
    "gambar_utama": "assets/kost_ibu_iza.png",
    "gambar_sub": "assets/kost_ibu_iza_2.png",
    "deskripsi": "Tersedia 1.kasur 2.lemari 3.meja kursi 4.kamar mandi di luar 5.dapur 6.parkir motor 7.fasilitas di lewati sarana angkot 8.dekat mall , puskesmas , stasiun , kampus , rumah sakit , sarana kuliner dll.Luas Kamar: 3 m x 3 m",
    "telepon": "082183356791",
    "alamat": "Jln margonda raya Gg.Ciliwung II Rt 02 / Rw 01 no:22 Kemiri muka beji Depok",
    "kota": "depok"
  },
  {
    "slug": "kost-19-residence-m",
    "nama_kost": "Kost 19 Residence M",
    "tipe": "WANITA",
    "sisa_kamar": "4 Sisa Kamar",
    "harga": "Rp. 2.249.000",
    "gambar_utama": "assets/K19_residence_M.png",
    "gambar_sub": "assets/K19_residence_M_2.png",
    "deskripsi": "KOS EKSKLUSIF PONDOK LABU – JAKSEL / CINERE Nyaman • Strategis • Aman Tersedia kamar di lantai 1 & 2 dengan 4 tipe kamar: S, M, L*, XL*** Cocok untuk mahasiswa maupun pekerja profesional. Fasilitas Kamar Kasur single bed Kursi & meja kerja Kulkas 1 pintu Lemari pakaian Kamar mandi dalam Kloset duduk & shower AC Internet cepat (WiFi + LAN) Listrik prabayar (token) Fasilitas Bersama Tempat cuci & jemuran Kompor gas (luar kamar) Microwave & mesin cuci bersama Satpam 24 jam & CCTV Parkir motor Parkir mobil (opsional) Lokasi Strategis 📍 Pondok Labu – Jakarta Selatan / Cinere UPN Veteran Jakarta Alfamart & ATM ± 80 m RS Puri Cinere 1,7 km Mall Cinere 1,9 km Gerbang Tol Andara (Depok–Antasari) 2,3 km RS Fatmawati 2,4 km Cilandak Town Square 3,3 km.Luas Kamar: 4 m x 5 m",
    "telepon": "0818165619",
    "alamat": "Taman Graha Indah K.19, Jl. Pangkalan Jati 2, Pangkalan Jati, Kec. Cinere, Kota Depok, Jawa Barat 16513.",
    "kota": "depok"
  },
  {
    "slug": "kost-kasmarani-residence",
    "nama_kost": "Kost Kasmarani Residence",
    "tipe": "CAMPURAN",
    "sisa_kamar": "3 Sisa Kamar",
    "harga": "Rp.800.000",
    "gambar_utama": "assets/kos_kasmarani_residence.png",
    "gambar_sub": "assets/kos_karmarani_residence_2.png",
    "deskripsi": "Kost Kasmarani Residence berlokasi ditempat strategis, 10 menit ke UNSRI dan POLSRI serta tempat umum lainnya, cocok untuk anak kuliahan atau bekerja. Kamar dengan luas 3 x 8 Meter, tidak termasuk biaya listrik, kami juga memiliki fasilitas parkir untuk mobil, motor, dan sepeda.",
    "telepon": "081261180375",
    "alamat": "Jl. Manunggal VI Jl. Manunggal V masuk dr, 30 Ilir, Kec. Ilir Bar. II, Kota Palembang, Sumatera Selatan.",
    "kota": "palembang"
  },
  {
    "slug": "kepatihan-6-tipe-eksklusif",
    "nama_kost": "Kepatihan 6 Tipe Eksklusif",
    "tipe": "CAMPURAN",
    "sisa_kamar": "4 Sisa Kamar",
    "harga": "Rp.750.000",
    "gambar_utama": "assets/kepatihan_6_tipe_eksklusif.png",
    "gambar_sub": "assets/kepatihan_6_tipe_eksklusif_2.png",
    "deskripsi": "Kamar fully furnished.Biaya elektronik (Kulkas) : Rp. 75,000Biaya elektronik (Dispenser) : Rp. 30,000Luas Kamar: 3 m x 3 m",
    "telepon": "082122554644",
    "alamat": "Jl. Veteran Gg. Kepatihan no. 6 Bogor Tengah 16125.",
    "kota": "bogor"
  },
  {
    "slug": "kost-fasilitas-lengkap-dan-termurah",
    "nama_kost": "Kost Fasilitas Lengkap dan Termurah",
    "tipe": "CAMPURAN",
    "sisa_kamar": "1 Sisa Kamar",
    "harga": "Rp. 700.000",
    "gambar_utama": "assets/kost_fasilitas_terlengkap_dan_termurah.png",
    "gambar_sub": "assets/kost_fasilitas_terlengkap_dan_termurah_2.png",
    "deskripsi": "Fasilitas Pribadi: - kasur - lemari - kursi - kamar mandi pribadi - token masing-masing Fasilitas Bersama: - kulkas - microwave - dispenser - kompor - parkiran motor - dapur - ruang tamu - balkon Akses: - Masjid 1 menit - Jalur angkot 2 menit - Indomaret 4 menit - Stasiun depok lama 6 menit - Terminal depok 7 menit.Luas Kamar: 4 m x 4 m",
    "telepon": "083820051004",
    "alamat": "Gg kembang ratu jaya cipayung depok.",
    "kota": "depok"
  },
  {
    "slug": "kost-ac-petamburan-tanah-abang",
    "nama_kost": "Kost AC Petamburan Tanah abang",
    "tipe": "CAMPURAN",
    "sisa_kamar": "1 Sisa Kamar",
    "harga": "Rp. 1.300.000",
    "gambar_utama": "assets/kost_AC_petamburan_tanah_abang.png",
    "gambar_sub": "assets/kost_AC_petamburan_tanah_abang_2.png",
    "deskripsi": "Fasilitas: AC Kasur Lemari Sudah termasuk listrik Kamar mandi di dalam kamar Lokasi: Indomaret dan Alfamaret 1 menit Jalur angkot 1 menit RS Pelni 2 menit Stasiun Tn Abang 4 menit Halte busway Slipi Petamburan 7 menit.Luas Kamar: 3 m x 3 m",
    "telepon": "083044052276",
    "alamat": "Gg kembang ratu jaya cipayung depok.",
    "kota": "depok"
  },
  {
    "slug": "kos-taman-kuliner",
    "nama_kost": "Kos Taman Kuliner",
    "tipe": "WANITA",
    "sisa_kamar": "1 Sisa Kamar",
    "harga": "Rp. 800.000",
    "gambar_utama": "assets/kos_taman_kuliner.png",
    "gambar_sub": "assets/kosan_taman_kuliner_2.png",
    "deskripsi": "Kosan yg nyaman dan asri, jauh dari kebisingan dan sejuk.Luas Kamar: 3 m x 3 m",
    "telepon": "082235772891",
    "alamat": "Near Gifari Nursery, Jl. Raya Bojongsari No.3, RT.3/RW.7, Bojongsari Baru, Kec. Bojongsari, Kota Depok, Jawa Barat 16516.",
    "kota": "depok"
  },
  {
    "slug": "mayesa-kost",
    "nama_kost": "Mayesa Kost",
    "tipe": "CAMPURAN",
    "sisa_kamar": "8 Sisa Kamar",
    "harga": "Rp. 650.000",
    "gambar_utama": "assets/mayesa_kost.png",
    "gambar_sub": "assets/mayesa_kost_2.png",
    "deskripsi": "Kost dekat jalan provinsi.Luas Kamar: 3 m x 4 m",
    "telepon": "082125283330",
    "alamat": "Jl. Ciputih gugahsari gg masjid albarokah RT 2 RW 3 Dramaga Bogor Jawa Barat.",
    "kota": "bogor"
  },
  {
    "slug": "kost-nabila",
    "nama_kost": "Kost Nabila",
    "tipe": "CAMPURAN",
    "sisa_kamar": "2 Sisa Kamar",
    "harga": "Rp. 1.600.000",
    "gambar_utama": "assets/kos_nabila.png",
    "gambar_sub": "assets/kos_nabila_2.png",
    "deskripsi": "Nabila kost berasa di pusat kota dan mudah di akses karena lokasinya yang berada di dekat Universitas Sriwijaya sehingga cocok untuk kost-kostan mahasiswa dan juga dekat dengan daerah perkantoran yang membuat nabila kost cocok untuk pekerja kantoran. Nabila kost bertemakan asri dan tentunya aman untuk dihuni.",
    "telepon": "0711375863",
    "alamat": "Lorong Anggrek No.1, Lorok Pakjo, Kec. Ilir Bar. I, Kota Palembang, Sumatera Selatan.",
    "kota": "palembang"
  },
  {
    "slug": "noor-kost-tawakal-3",
    "nama_kost": "Noor Kost Tawakal 3",
    "tipe": "WANITA",
    "sisa_kamar": "6 Sisa Kamar",
    "harga": "Rp. 1.000.000",
    "gambar_utama": "assets/noor_kost_tawakal.png",
    "gambar_sub": "assets/noor_kost_tawakal_2.png",
    "deskripsi": "Cari kost dengan konsep islami yang nyaman dan insyaa Allah bikin tenang dan aman di daerah Sentul? Insyaa Allah Noor Kost bisa jadi solusinya! Nikmati fasilitas lengkap dengan sentuhan islami, mulai dari kamar tidur yang bersih dan nyaman, ruang bersama dengan nuansa islami, dan juga masjid Az-Zikra yang dekat dengan lokasi kost. Dengan lokasinya yang berada di perumahan Az-Zikra, kamu dapat menikmati kemudahan akses ke pusat perbelanjaan, universitas, jalan tol, restoran, kafe, dan fasili.Luas Kamar: 3 m x 2 m",
    "telepon": "082122554644",
    "alamat": "Jl. Tawakal III No.20, Cipambuan, Kec. Babakan Madang, Kabupaten Bogor, Jawa Barat 16810, Indonesia.",
    "kota": "bogor"
  },
  {
    "slug": "owl-residence",
    "nama_kost": "Owl Residence",
    "tipe": "WANITA",
    "sisa_kamar": "5 Sisa Kamar",
    "harga": "Rp. 1.700.000",
    "gambar_utama": "assets/owl_residence.png",
    "gambar_sub": "assets/owl_residence_2.png",
    "deskripsi": "Kost baru yang bertema simple modern, nyaman, dan terjangkau. Lokasi dalam kompleks perumahan dijaga satpam. Smart door lock dengan kartu akses Dapur dan ruang bersantai untuk bersama Kulkas Listrik dengan digital KWH meter setiap kamar Room cleaning sekali per minggu Free parkir mobil dan motor CCTV 24 jam Dalam kamar: WiFi 3o mbps AC 1 pk Springbed 100x200 Sprei set, 2 bantal Lemari besar 2 pintu Meja belajar dengan kursi Tempat sampah Kost tinggal masuk, siap huni!.Luas Kamar: 3 m x 4 m",
    "telepon": "085840002076",
    "alamat": "Owl Residence Jl. Taman Madrid 1 No.41 Blok F1, RT.001/RW.015, Nagrak, Kec. Gn. Putri, Kabupaten Bogor, Jawa Barat 16968.",
    "kota": "bogor"
  },
  {
    "slug": "kost-puncak",
    "nama_kost": "Kost Puncak",
    "tipe": "CAMPURAN",
    "sisa_kamar": "1 Sisa Kamar",
    "harga": "Rp. 1.400.000",
    "gambar_utama": "assets/kos_puncak_2.png",
    "gambar_sub": "assets/kos_puncak.png",
    "deskripsi": "Kost Puncak berlokasi ditempat strategis, 10 menit ke UNSRI dan POLSRI serta tempat umum lainnya, cocok untuk anak kuliahan atau bekerja. Kamar dengan luas 3 x 8 Meter, tidak termasuk biaya listrik, kami juga memiliki fasilitas parkir untuk mobil, motor, dan sepeda.",
    "telepon": "081377700825",
    "alamat": "Deket SMAN2, Samping Apotik Puncak, Jl. Puncak Sekuning, Kota Palembang, Sumatera Selatan.",
    "kota": "palembang"
  },
  {
    "slug": "roemah-kost",
    "nama_kost": "Roemah kost",
    "tipe": "WANITA",
    "sisa_kamar": "5 Sisa Kamar",
    "harga": "Rp.1.100.000",
    "gambar_utama": "assets/Roemah_Kost.png",
    "gambar_sub": "assets/Roemah_Kost.png",
    "deskripsi": "Kost khusus Putri.Luas Kamar: 9 m x 3 m",
    "telepon": "082122356744",
    "alamat": "Limus Pratama Regency, Jl. Narogong Raya Blok B6-25 Cileungsi Bogor.",
    "kota": "bogor"
  },
  {
    "slug": "kost-ronan-putra",
    "nama_kost": "Kost Ronan Putra",
    "tipe": "PRIA",
    "sisa_kamar": "2 Sisa Kamar",
    "harga": "Rp.1.400.000",
    "gambar_utama": "assets/kos_ronan_putra.png",
    "gambar_sub": "assets/kos_ronan_putra_2.png",
    "deskripsi": "Kost Ronan Putra berlokasi ditempat strategis, 10 menit ke UNSRI dan POLSRI serta tempat umum lainnya, cocok untuk anak kuliahan atau bekerja. Kamar dengan luas 3 x 8 Meter, tidak termasuk biaya listrik, kami juga memiliki fasilitas parkir untuk mobil, motor, dan sepeda.",
    "telepon": "087881171736",
    "alamat": "Jl. Putri Rambut Selako Gg. Surya No.42B, RT.22, Bukit Lama, Kec. Ilir Bar. I, Kota Palembang, Sumatera Selatan.",
    "kota": "palembang"
  },
  {
    "slug": "kost-sheva",
    "nama_kost": "Kost Sheva",
    "tipe": "CAMPURAN",
    "sisa_kamar": "1 Sisa Kamar",
    "harga": "Rp. 1.400.000",
    "gambar_utama": "assets/kos_sheva.png",
    "gambar_sub": "assets/kos_sheva_2.png",
    "deskripsi": "Kost Strategis dan Terjangkau, Hanya +/- 150 meter dari Jalan Demang Lebar Daun, sangat dekat dengan berbagai fasilitas umum, jarak hanya 5 menit ke Universitas Sriwijaya Bukit, SMA 1, SMA 5, SMA 10 Palembang, 7 menit ke Palembang Square Mall & RS Bunda, kamar mandi dalam+shower, dapur+wastafel pribadi (Stok terbatas), AC, lemari, springbed, parkir luas bisa untuk banyak mobil, dapur umum (FREE AIR GALON & GAS), ruang santai, free Wifi & PDAM, CCTV 24 jam, ada tipe kontrakan & tipe kamar.",
    "telepon": "081367624400",
    "alamat": "Bukit Baru, Kec. Ilir Bar. I, Kota Palembang, Sumatera Selatan.",
    "kota": "palembang"
  },
  {
    "slug": "kos-taman-siliwangi-depok",
    "nama_kost": "Kos Taman Siliwangi Depok",
    "tipe": "WANITA",
    "sisa_kamar": "6 Sisa Kamar",
    "harga": "Rp. 850.000",
    "gambar_utama": "assets/kost_taman_siliwangi_depok.png",
    "gambar_sub": "assets/kost_taman_siliwangi_depok_2.png",
    "deskripsi": "Tempat tidur Kasur Bantal Guling Lemari Kursi plastik Kipas angin Sprei Wifi Ruang jemur Taman Kulkas.Luas Kamar: 4 m x 2 m",
    "telepon": "085830227085",
    "alamat": "Perumahan Taman Siliwangi Blok E No.4 Depok.",
    "kota": "depok"
  },
  {
    "slug": "tiga-saudara-kost",
    "nama_kost": "Tiga Saudara Kost",
    "tipe": "CAMPURAN",
    "sisa_kamar": "1 Sisa Kamar",
    "harga": "Rp.700.000",
    "gambar_utama": "assets/kos_tiga_saudara.png",
    "gambar_sub": "assets/tiga_saudara_kost_2.jpeg",
    "deskripsi": "Tiga Saudara Kost berlokasi ditempat strategis, 10 menit ke UNSRI dan POLSRI serta tempat umum lainnya, cocok untuk anak kuliahan atau bekerja. Tidak termasuk biaya listrik dan air, kami juga memiliki fasilitas parkir untuk mobil, motor, dan sepeda.",
    "telepon": "082182273592",
    "alamat": "Jl. Macan Lindungan, Bukit Baru, Kec. Ilir Bar. I, Kota Palembang, Sumatera Selatan 30138",
    "kota": "palembang"
  },
  {
    "slug": "trie-kost-depok",
    "nama_kost": "Trie Kost Depok",
    "tipe": "CAMPURAN",
    "sisa_kamar": "10 Sisa Kamar",
    "harga": "Rp. 1.250.000",
    "gambar_utama": "assets/trie_kost_depok_dekat_stasiun_depok_lama.png",
    "gambar_sub": "assets/trie_kost_depok_dekat_stasiun_depok_lama_2.png",
    "deskripsi": "Fasilitas: Terima Kos di lokasi sangat strategis dekat stasiun depok lama, Bangunan Baru, Bebas Akses 24 jam Fasilitas : [-AC-] [-FREE WI-FI-] [-Dipan kayu Jepara + kasur Inoac-] [-Lemari kayu Baru-] [-WC dalam semua-] [-Shower-] [-Toilet duduk-] [-Listrik token 1300watt-] [-Dapur bersama -] [-Ruang jemur-] [-Kulkas-] Fasilitas Umum : [-Dapur Bersama-] [-Kulkas-] [-Parkiran Motor-] [-Sofa & Meja Tamu-] [- Ruang Jemur-] Lokasi sangat strategis seberang stasiun \n                        depok lama, tepat di belakang kantor pajak Depok, untuk \n                        yang bersama pasangan wajib memperlihatkan surat nikah selain \n                        itu maaf tidak bisa Non AC 950rb AC 1.25jt.Luas Kamar: 3 m x 4 m",
    "telepon": "082183275590",
    "alamat": "Jl. Belimbing II No.46, RT.2/RW.1, Depok, Kec. Pancoran Mas, Kota Depok, Jawa Barat 16431.",
    "kota": "depok"
  },
  {
    "slug": "kos-wanita-salkia",
    "nama_kost": "Kos Wanita Salkia",
    "tipe": "WANITA",
    "sisa_kamar": "10 Sisa Kamar",
    "harga": "Rp. 1.500.000",
    "gambar_utama": "assets/kos_wanita_salkia.png",
    "gambar_sub": "assets/kos_wanita_salkia_2.png",
    "deskripsi": "Berletak di belakang gerbang Kampus UI.Luas Kamar: 3 m x 6 m",
    "telepon": "082235402291",
    "alamat": "Jl. Kabel No. 12 RT. 004/005 Kukusan, Beji Depok.",
    "kota": "depok"
  },
  {
    "slug": "winter-room-bronze-type",
    "nama_kost": "Winter Room Bronze Type",
    "tipe": "WANITA",
    "sisa_kamar": "7 Sisa Kamar",
    "harga": "Rp. 1.700.000",
    "gambar_utama": "assets/winter_room_bronze_type.png",
    "gambar_sub": "assets/winter_room_bronze_type_2.png",
    "deskripsi": "Kost khusus putri, lokasi strategis, dekat dengan alfamart, jajanan makanan, sekolah, laundry service, mesjid, pusat perbelanjaan (D'Mall), halte bus (Bus stop: kedondong), stasiun kereta api (Pondok cina dan Depok Baru), terminal bus (untuk bus bandara), dan Pintu masuk tol Cijago - Antasari. Fasilitas: - Kamar mandi dalam - Water Heater - WIFI - AC - Full-furnished - Single bed Fasilitas bersama: - Area parkir - Dapur bersama - Ruang makan bersama - Loker - Open space area - CCTV & security 24 jam Dapatkan kost dengan fasilitas dan kenyamanan hotek bintang lima dengan pelayanan first class service dan harga terjangkau..Luas Kamar: 3 m x 4 m",
    "telepon": "083560774502",
    "alamat": "Jl. Kemirimuka No. 48D, RT/RW 01/015, Kelurahan Kemiri muka, Kecamatan Beji, Depok, Jawa Barat, Indonesia, 16423.",
    "kota": "depok"
  }
];

export default dataKos;